Setup postgres repo
chaindexing/chaindexing-ts pull request #5
Opened 2023-11-23 17:36 UTC by conquext

The PR contains basic setup for the postgres repo extending from the abstract repo class.

2023-11-24 13:37 UTC, Jurshsmith requested changes
Looks good. 🚀 Just a few tiny detail comments and updating the stale `ContractAddress` fields.

2023-11-24 13:37 UTC, Jurshsmith commented on chaindexing-postgres/src/drizzle/db.ts
> +  connectionString: 'postgres://user:password@host:port/db'
A bit early, but let's set the maximum parallel connections allowed:

```suggestion
  connectionString: 'postgres://user:password@host:port/db',
  max: 2
```

2023-11-24 13:37 UTC, Jurshsmith commented on chaindexing-postgres/src/drizzle/schema.ts
> +);
Nice 👍🏾

2023-11-24 13:37 UTC, Jurshsmith commented on chaindexing-postgres/src/drizzle/schema.ts
> +    startBlockNumber: integer('start_block_number'),
Sorry, forgot to mention. Some of these fields are stale.

```suggestion
    startBlockNumber: integer('start_block_number'),
    nextBlockNumberToIngestFrom: integer('next_block_number_to_ingest_from'),
    nextBlockNumberToHandleFrom: integer('next_block_number_to_handler_from'),
```

2023-11-24 13:37 UTC, Jurshsmith commented on chaindexing-postgres/src/repo.postgres.ts
> +  async createEvents(_conn: Conn, _events: any) {
Nit: `Event` interface exists

```suggestion
  async createEvents(_conn: Conn, _events: Event[]) {
```

2023-11-24 13:37 UTC, Jurshsmith commented on chaindexing-repos/src/index.ts
> +    repoOps: (transaction_conn: Conn) => Promise<void>
Nice 👍🏾

2023-11-24 13:37 UTC, Jurshsmith commented on chaindexing-postgres/src/repo.postgres.ts
> +  conn?: Conn;
These should not exist in the Repo object. 

```suggestion
  
```

2023-11-27 05:53 UTC, conquext commented
> Looks good. 🚀 Just a few tiny detail comments and updating the stale `ContractAddress` fields.

The issues have been resolved accordingly.

2023-11-27 21:36 UTC, Jurshsmith approved these changes

2023-11-27 21:36 UTC, merged